### PR TITLE
Load resources according to AA namespace

### PR DESCRIPTION
**Pull request by alexey**
Fix an issue when namespace is not default but something like:
`config.default_namespace = :cia_admin`

### CODE REVIEW

**Comment by yhirano55** [comment]
Thanks for your contribution.

**Comment by alexey** [comment]
Hi ! Thanks for accepting PR fast.

Do you may have idea why i cannot assign roles in batch actions in
AdminUser model ? i see only default.
2.4.1, Rails 5, AA 2.0.0.alpha



ср, 13 сент. 2017 г. в 18:44, yhirano55 <notifications@github.com>:

**Comment by yhirano55** [comment]
@alexey Ah...sorry, I don't recently use AA on my project. According to my super old memory, maybe batch actions are not general action method, and they have conditions per action (It's not correct information, so please get correct ones by yourself). I'm sorry that I cannot help you.

**Comment by yhirano55** [comment]
I've remind. Batch action can assign, but it cannot define per condition (e.g. create, update, destroy...etc). Batch action is one of action, and it has processes per condition inside it. For more information, please check AA code by yourself.

**Pull request merged**
